// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctjhdlczfbteqqksqptk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0amhkbGN6ZmJ0ZXFxa3NxcHRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDEwNzcsImV4cCI6MjA2OTgxNzA3N30.yqs73YERqyIEckyY62UX2foSpeFvoJJBFV32tkniMOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});